import mongoose from "mongoose";

const metricSchema = new mongoose.Schema(
  {
    value: String,
    label: String,
  },
  { _id: false },
);

const valuePropSchema = new mongoose.Schema(
  {
    title: String,
    text: String,
    iconKey: String,
  },
  { _id: false },
);

const brandConfigSchema = new mongoose.Schema({
  brandKey: { type: String, required: true, unique: true },
  displayName: { type: String, required: true },
  logo: {
    light: String,
    dark: String,
  },
  theme: {
    primaryColor: String,
    secondaryColor: String,
    fontFamily: String,
  },
  paymentGateways: [
    {
      provider: String,
      isActive: Boolean,
      config: mongoose.Schema.Types.Mixed,
    },
  ],
  shippingRules: [
    {
      method: String,
      carriers: [String],
      feeSchedule: mongoose.Schema.Types.Mixed,
    },
  ],
  taxRate: Number,
  supportEmail: String,
  supportPhone: String,
  socialLinks: {
    facebook: String,
    instagram: String,
    tiktok: String,
    youtube: String,
  },
  featureFlags: {
    loyalty: { type: Boolean, default: true },
    flashSale: { type: Boolean, default: true },
    review: { type: Boolean, default: true },
  },
  storefront: {
    home: {
      hero: {
        kicker: String,
        titleLine1: String,
        titleLine2: String,
        description: String,
        primaryCtaLabel: String,
        secondaryCtaLabel: String,
        dealDescription: String,
        sideKicker: String,
        sideTitleLine1: String,
        sideTitleLine2: String,
        sideDescription: String,
        dealCtaLabel: String,
        sideCtaLabel: String,
        metrics: [metricSchema],
      },
      sections: {
        categoriesMiniTitle: String,
        categoriesTitle: String,
        categoriesLinkLabel: String,
        categoryMosaicKicker: String,
        showcaseKicker: String,
        showcaseTitle: String,
        showcaseDescription: String,
        flashSaleMiniTitle: String,
        flashSaleTitle: String,
        flashSaleLinkLabel: String,
        productsMiniTitle: String,
        productsTitle: String,
        productsLinkLabel: String,
        curatedKicker: String,
        curatedTitle: String,
        curatedDescription: String,
        curatedLinkLabel: String,
        collectionKicker: String,
        collectionLinkLabel: String,
        couponKicker: String,
        couponTitle: String,
        couponLinkLabel: String,
      },
      labels: {
        flashDeal: String,
        soldPercentPrefix: String,
        soldOutSoon: String,
        dealFallbackTitle: String,
        buyDeal: String,
        exploreNow: String,
        noCategories: String,
        noFlashSales: String,
        noProducts: String,
        loadingCategories: String,
        loadingFlashSales: String,
        loadingProducts: String,
        loadingHome: String,
        heroPriceLabel: String,
        heroSignalLabel: String,
        heroSlideSecondaryLabel: String,
        updatingLabel: String,
        productOpenLabel: String,
        shoppingCategoryLabel: String,
        activeDealLabel: String,
        sameDayFulfillmentLabel: String,
        topCategoryBadgeLabel: String,
        categoryDefaultBadge: String,
        categoryBestSellerBadge: String,
        categoryNewBadge: String,
        categoryPromotionBadge: String,
        soldUpdatedLabel: String,
        couponSavedLabel: String,
        couponSaveLabel: String,
        couponAlreadySavedMessage: String,
        couponSavedAndCopiedMessage: String,
        couponSavedMessage: String,
        viewCategoryLabel: String,
      },
      valueProps: [valuePropSchema],
      journal: {
        kicker: String,
        titleLine1: String,
        titleLine2: String,
        description: String,
        ctaLabel: String,
      },
      member: {
        kicker: String,
        title: String,
        description: String,
        emailPlaceholder: String,
        ctaLabel: String,
        loggedInTitle: String,
        loggedInDescription: String,
        loggedInCtaLabel: String,
      },
      apiNotice: String,
    },
  },
  maintenanceMode: { type: Boolean, default: false },
  updatedAt: { type: Date, default: Date.now },
});

// Indexes
export default mongoose.model("BrandConfig", brandConfigSchema);
